{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status microservices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "bill-database",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"bills_database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "car-statistics-database",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"car_statistics_database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start-stop-database",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"start_stop\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tracking-infos-database",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"tracking_infos_database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "anti-fraud-analyzer",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "anti_fraud_analyzer_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "billing-handler",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "expr": "billing_handler_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "car-tracker",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "targets": [
    { "expr": "car_tracker_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "client-communication-service",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "client_communication_service_service_up",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "route-advisor",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    { "expr": "route_advisor_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tracking-analytics",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "targets": [
    { "expr": "tracking_analytics_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tracking-shutdown",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "targets": [
    { "expr": "tracking_shutdown_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "user-configurator",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "targets": [
    { "expr": "user_configurator_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "camera-checker",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "mock_camera_checker_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "user-position-proxy",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "targets": [
    { "expr": "user_position_proxy_service_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mock-zone-pollution-extern",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "mock_zones_pollution_extern_service_up",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "mocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Zone pollution - number of zones requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "delta(mock_zones_pollution_extern_number_of_get_zones_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Camera - number of camera check requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "delta(mock_camera_checker_number_of_camera_checks_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "user-configurator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Number of car start events received / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "delta(user_configurator_number_of_car_start_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car position events received / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "delta(user_configurator_number_of_car_position_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of external requests./ min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "delta(user_configurator_number_of_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of success external requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 31 },
   "targets": [
    {
     "expr": "delta(user_configurator_number_of_success_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed external requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 31 },
   "targets": [
    {
     "expr": "delta(user_configurator_number_of_failed_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "tracking-shutdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Number of car shutdown events received / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "delta(tracking_shutdown_number_of_car_shutdown_events_received[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of external requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 40 },
   "targets": [
    {
     "expr": "delta(tracking_shutdown_number_of_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of success external requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 40 },
   "targets": [
    {
     "expr": "delta(tracking_shutdown_number_of_success_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed external requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "delta(tracking_shutdown_number_of_failed_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of database call / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 40 },
   "targets": [
    {
     "expr": "delta(tracking_shutdown_number_of_database_call[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "tracking-analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number of new analytics requests / minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "delta(tracking_analytics_number_of_new_analytics_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of database calls / minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "delta(tracking_analytics_number_of_database_call[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "route-advisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Number of asked route event requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "delta(route_advisor_number_of_asked_routes_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of external requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "expr": "delta(route_advisor_number_of_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of success external requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "delta(route_advisor_number_of_success_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed external requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "targets": [
    {
     "expr": "delta(route_advisor_number_of_failed_external_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "client-communication-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "number of new frequencies received by system / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "delta(client_communication_service_number_of_new_frequencies_received_by_system[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of new frequencies received by system / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "targets": [
    {
     "expr": "delta(client_communication_service_number_of_new_frequencies_received_by_system[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of messages send by socket / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "delta(client_communication_service_number_of_messages_send_via_socket[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "number of users connected to socket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "targets": [
    {
     "expr": "client_communication_service_number_of_users_connected_to_socket",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "user-position-proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Number of car starts / minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "delta(user_position_proxy_number_of_car_start_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car positions / minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 76 },
   "targets": [
    {
     "expr": "delta(user_position_proxy_number_of_car_position_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car stop / minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "delta(user_position_proxy_number_of_car_stop_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car asking route / minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 76 },
   "targets": [
    {
     "expr": "delta(user_position_proxy_number_of_car_asking_route_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "bill-database",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"bills_database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "car-statistics-database",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"car_statistics_database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "start-stop-database",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"start_stop\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tracking-infos-database",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"tracking_infos_database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "car-tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Number of output request / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_output_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of success output request / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 90 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_success_output_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed output request / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 90 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_failed_output_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of caches calls / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_cache_request[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of database calls / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 90 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_database_call[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 90 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of tracking shutdown emit events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_tracking_shutdown_emit_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car start input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 96 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_car_start_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car position input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_car_position_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car stop input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 96 },
   "targets": [
    {
     "expr": "delta(car_tracker_number_of_car_stop_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "billing-handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Number of input request / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "delta(billing_handler_number_of_input_request[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of system input request / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 103 },
   "targets": [
    {
     "expr": "delta(billing_handler_number_of_system_input_request[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of user input request / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "delta(billing_handler_number_of_user_input_request[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of database calls / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 103 },
   "targets": [
    {
     "expr": "delta(billing_handler_number_of_database_call[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "anti-fraud-analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Number of input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of output requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 110 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_output_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of success output requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_success_output_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of failed output requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 110 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_failed_output_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of database call / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_database_call[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car start input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 116 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_car_start_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car position input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_car_position_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of car stop input events / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 116 },
   "targets": [
    {
     "expr": "delta(anti_fraud_analyzer_number_of_car_stop_input_events[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}