
### Send start to the bus
GET http://localhost:6809/start
Accept: application/json

### Send position to the bus
GET http://localhost:6809/position
Accept: application/json

### Send stop to the bus
GET http://localhost:6809/stop
Accept: application/json


### Test
GET http://localhost:6808/
Accept: application/json
