### Create a new car
POST http://localhost:6808/start-car
Content-Type: application/json

{
  "license_plate": "DA267EF"
}

### Edit interval for cart
POST http://localhost:6808/edit-request-interval
Content-Type: application/json

{
  "license_plate": "DA267EF",
  "interval": 2
}

### Stop car
POST http://localhost:6808/stop-car
Content-Type: application/json

{
  "license_plate": "DA267EF"
}

### Get bills
GET http://localhost:6803/
Content-Type: application/json

### Get User billes
GET http://localhost:6803/user-bills/DA267EF
Content-Type: application/json

### Pay billes
PUT http://localhost:6803/pay-bill/6373430b8d4888de71ecb484
Content-Type: application/json
