### Create a new car
POST http://51.38.71.146:6808/start-car
Content-Type: application/json

{
  "license_plate": "DA258EF"
}

### Edit interval for cart
POST http://51.38.71.146:6808/edit-request-interval
Content-Type: application/json

{
  "license_plate": "DA258EF",
  "interval": 1
}

### Stop car
POST http://51.38.71.146:6808/stop-car
Content-Type: application/json

{
  "license_plate": "DA258EF"
}

### Get bills
GET http://51.38.71.146:6803/
Content-Type: application/json

### Get User billes
GET http://51.38.71.146:6803/user-bills/DA258EF
Content-Type: application/json

### Pay billes
PUT http://51.38.71.146:6803/pay-bill/63729d6f9f7c32cdf3d56742
Content-Type: application/json
