### Create a new car
POST http://localhost:6808/start-car
Content-Type: application/json

{
  "license_plate": "VB-947-SD"
}

### Edit interval for cart
POST http://localhost:6808/edit-request-interval
Content-Type: application/json

{
  "license_plate": "VB-947-SD",
  "interval": 5
}

### Stop car
POST http://localhost:6808/stop-car
Content-Type: application/json

{
  "license_plate": "VB-947-SD"
}
