### Create a new car
POST http://localhost:6808/start-car
Content-Type: application/json

{
  "license_plate": "10"
}

### Edit interval for cart
POST http://localhost:6808/edit-request-interval
Content-Type: application/json

{
  "license_plate": "10",
  "interval": 0.1
}

### Stop car
POST http://localhost:6808/stop-car
Content-Type: application/json

{
  "license_plate": "10"
}
