name: "Build Dev docker containers"

on: [push, pull_request]

jobs:
  build-billing-handler-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development billing handler
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build billing-handler
