name: "Build Dev docker containers"

on: [push, pull_request]

jobs:
  build-anti-fraud-analyzer-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development anti-fraud-analyzer
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build anti-fraud-analyzer

  build-billing-handler-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development billing-handler
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build billing-handler

  build-car-tracker-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development car-tracker
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build car-tracker

  build-client-communication-service-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the productdevelopment-communication-service
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build client-communication-service

  build-route-advisor-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development route-advisor
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build route-advisor

  build-tracking-analytics-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development tracking-analytics
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build tracking-analytics

  build-tracking-shutdown-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development tracking-shutdown
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build tracking-shutdown

  build-user-configurator-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development user-configurator
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build user-configurator

  build-user-position-proxy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development user-position-proxy
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build user-position-proxy

  build-camera-checker-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development camera-checker
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build camera-checker

  build-zones-pollution-extern-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the producdevelopment-pollution-extern
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build zones-pollution-extern

