name: "Build Dev docker containers"

on: [push, pull_request]

jobs:
  build-billing-handler-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development billing handler
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build billing-handler

  build-car-tracker-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development car-tracker
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build car-tracker

  build-pollution-zone-aggregatorr-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development pollution-zone-aggregator
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build pollution-zone-aggregator

  build-position-checker-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development position-checker
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build position-checker

  build-tracking-shutdown-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development tracking-shutdown
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build tracking-shutdown

  build-mock-camera-checker-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development mock-camera-checker
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build mock-camera-checker

  build-mock-pollution-zones-emitter-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the development mock-pollution-zones-emitter
        working-directory: ./project
        run: docker-compose --file ./docker-compose-dev.yml build mock-pollution-zones-emitter
